from enum import Enum


class HookError(Enum):
    HOOK_NOT_EXIST_ERROR = 'HOOK_NOT_EXIST_ERROR'
    HOOK_ALREDY_EXIST_ERROR = 'HOOK_ALREDY_EXIST_ERROR'
    HOOK_NOT_ACTIVE_ERROR = 'HOOK_NOT_ACTIVE_ERROR'
