from enum import Enum


class JobError(Enum):
    EXECUTE_WORK_ERROR = 'EXECUTE_WORK_ERROR'
    WORK_NOT_EXIST_ERROR = 'WORK_NOT_EXIST_ERROR'
    WORK_NOT_RUNNING_ERROR = 'WORK_NOT_RUNNING_ERROR'
    WORK_INVALID_STATUS_ERROR = 'WORK_INVALID_STATUS_ERROR'
    WORK_SAME_STATUS_ERROR = 'WORK_SAME_STATUS_ERROR'
